import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'

const root = process.cwd()
const outputFile = path.join(root, 'src/components/trading/model/featureSpecRegistry.generated.ts')
const checkOnly = process.argv.includes('--check')

const pythonCode = `
import json
from trading_trainer.features.specs import get_feature_spec

specs = []
for index in range(1, 500):
    version = f"v{index:03d}"
    try:
        spec = get_feature_spec(version)
    except Exception:
        if specs:
            break
        continue
    specs.append({
        "version": spec.version,
        "interval": spec.interval,
        "lookbackBars": int(spec.lookbackBars),
        "columns": list(spec.columns),
        "columnCount": len(spec.columns),
    })

print(json.dumps(specs, ensure_ascii=False))
`.trim()

const runPython = () => {
  const candidates = [process.env.PYTHON_BIN, 'python3', 'python'].filter((item) => typeof item === 'string' && item.length > 0)
  const errors = []

  for (const candidate of candidates) {
    const env = { ...process.env }
    env.PYTHONPATH = [path.join(root, 'python'), env.PYTHONPATH].filter(Boolean).join(path.delimiter)
    const result = spawnSync(candidate, ['-c', pythonCode], {
      cwd: root,
      env,
      encoding: 'utf8',
    })

    if (result.status === 0) {
      return {
        ok: true,
        pythonBin: candidate,
        stdout: (result.stdout || '').trim(),
      }
    }

    const stderr = (result.stderr || '').trim()
    const stdout = (result.stdout || '').trim()
    const detail = stderr || stdout || `exit=${result.status}`
    errors.push(`${candidate}: ${detail}`)
  }

  return {
    ok: false,
    errors,
  }
}

const pythonResult = runPython()
if (!pythonResult.ok) {
  console.error('[feature-spec-sync] Failed to read specs from Python:')
  for (const error of pythonResult.errors) console.error(`- ${error}`)
  process.exit(1)
}

/** @type {Array<{version: string, interval: string, lookbackBars: number, columns: string[], columnCount: number}>} */
let specs

try {
  const parsed = JSON.parse(pythonResult.stdout)
  if (!Array.isArray(parsed) || parsed.length === 0) {
    throw new Error('empty spec list')
  }
  specs = parsed
} catch (error) {
  console.error(`[feature-spec-sync] Invalid JSON from Python: ${error instanceof Error ? error.message : String(error)}`)
  process.exit(1)
}

const content = `/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Source of truth: python/trading_trainer/features/specs.py
// Generated by: node scripts/sync_feature_specs.mjs

export interface PythonFeatureSpecContract {
  version: string
  interval: string
  lookbackBars: number
  columns: string[]
  columnCount: number
}

export const PYTHON_FEATURE_SPECS: PythonFeatureSpecContract[] = ${JSON.stringify(specs, null, 2)}

export const LATEST_PYTHON_FEATURE_SPEC_VERSION = PYTHON_FEATURE_SPECS[PYTHON_FEATURE_SPECS.length - 1]?.version ?? 'v001'
`

if (checkOnly) {
  if (!fs.existsSync(outputFile)) {
    console.error(`[feature-spec-sync] Missing generated file: ${path.relative(root, outputFile)}`)
    process.exit(1)
  }
  const current = fs.readFileSync(outputFile, 'utf8')
  if (current !== content) {
    console.error('[feature-spec-sync] Generated feature spec registry is out of date.')
    console.error('[feature-spec-sync] Run: node scripts/sync_feature_specs.mjs')
    process.exit(1)
  }
  console.log(`[feature-spec-sync] OK (${specs.length} specs, ${pythonResult.pythonBin})`)
  process.exit(0)
}

fs.writeFileSync(outputFile, content, 'utf8')
console.log(`[feature-spec-sync] Wrote ${path.relative(root, outputFile)} (${specs.length} specs, ${pythonResult.pythonBin})`)
